[files]
extend-exclude = [
    "Cargo.lock",
    "LICENSE",
    "apple/licenses/THIRD_PARTY_NOTICES-*.txt",
]

[default.extend-words]
Gmail = "Gmail"
PKCE = "PKCE"
Slint = "Slint"
tersa = "tersa"
WKWebView = "WKWebView"
WRONLY = "WRONLY"
