# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

[advisories]
version = 2
yanked = "deny"
unmaintained = "all"

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"

[licenses]
version = 2
confidence-threshold = 0.8
allow = [
    "Apache-2.0",
    "MIT",
    "MPL-2.0",
    "Unicode-3.0",
]

exceptions = [
    { allow = ["NCSA"], name = "libfuzzer-sys", version = "=0.4.13" },
]

[sources]
unknown-git = "deny"
unknown-registry = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
